### ISSUE TITLE
source package dependency trees

### ISSUE THREAD

**Issue by jimhester** [r-lib/pkginstall#12]

**Comment by gaborcsardi** [comment]
`pkgdepends` can provide this, of course. 

To clarify, binary packages must be included as well, because they might be needed to install the source packages. What format would you like that allows easy parallel installs? 

The dependency graph is a DAG, and as soon as all dependencies of a source package are installed, it can be installed as well. Binary packages have no outgoing edges in the DAG, they can be installed immediately.

**Comment by jimhester** [comment]
Yeah just the DAG for dependencies, I just need to take this into account when installing source packages (particularly in parallel), right now we do not do so in anyway.

**Comment by jimhester** [comment]
So assuming we have a DAG like the following we can install each horizontal level in parallel (in this case binary packages would be unconnected nodes at the top level), so the easiest input would just be a list of character vectors representing each level down the graph. This is maybe not the maximally optimal way to do it but seems to be fairly easy to implement. Ignore the names of the nodes, it was mainly for the layout.

![graph](https://i.stack.imgur.com/3STCP.png)

**Comment by gaborcsardi** [comment]
I think we can do better/easier than that. I will just give you a list, with a character vector for each package to install. The character vectors contain package names. These are the dependencies for each installation. 

1. Whenever a package is installed you remove it from all character vectors (`x <- lapply(x, setdiff, pkg)`). You can also remove its vector from the list, obviously.
2. Whenever the vector of a package gets empty, you can start installing it.

That's all I think.

**Comment by jimhester** [comment]
I don't see how you sync the parallel processes with this algorithm?

**Comment by gaborcsardi** [comment]
You can just start a new one for each install.

**Comment by jimhester** [comment]
Ah I see, yes that should work.

**Comment by gaborcsardi** [comment]
If the startup time is too much, then we can fix that later by reusing the process.

**Comment by gaborcsardi** [comment]
If you don't want to start too many processes, put the "installable" packages in a queue (well, a character vector), and take one from that, as soon as a "worker" is done.

**Comment by gaborcsardi** [comment]
I am working on producing this, btw. but the resolution of what packages you actually need to install, and which versions of them, is slightly involved.

**Comment by gaborcsardi** [comment]
OK, I have sg that you can test. It is not perfect, in particular
- [ ] it does not treat recommended packaged specially yet
- [ ] it fails badly if the package(s) cannot be installed because of conflicts
- [ ] the cache dir(s) are not set up properly, you need to provide a directory manually

These will be fixed soon. This is how it works:
```r
r <- remotes$new(
  c("igraph", "r-lib/rcmdcheck"),
  config = list(cache_dir = "/tmp/cache"), 
  library = "/tmp/library")
res <- r$resolve()
sol <- r$solve()
dl <- r$download_solution()
r$get_install_plan()
```
which gives you sg like this:
```
# A tibble: 20 x 6
       package      type    version
         <chr>     <chr>      <chr>
 1    processx      cran    2.0.0.1
 2   backports      cran      1.1.1
 3  assertthat      cran      0.2.0
 4      Matrix      cran     1.2-11
 5    magrittr      cran        1.5
 6   rprojroot      cran        1.2
 7  clisymbols      cran      1.2.0
 8 prettyunits      cran      1.0.2
 9       withr      cran      2.0.0
10        desc installed 1.1.1.9000
11      igraph      cran      1.1.2
12          R6 installed      2.2.2
13      crayon      cran      1.3.4
14     debugme      cran      1.0.2
15      digest      cran     0.6.12
16       irlba      cran      2.2.1
17   rcmdcheck    github 1.2.1.9002
18   pkgconfig      cran      2.0.1
19       callr    github 1.0.0.9000
20     lattice      cran    0.20-35
# ... with 3 more variables: file <chr>, binary <lgl>, dependencies <S3: AsIs>
```
(`sol` is a more complete version of this.) `dependencies` will just list the dependent packages, so you can use that for the installation order:
```r
❯ r$get_install_plan()$dependencies[1:5]
[[1]]
[1] "assertthat" "crayon"     "debugme"    "R6"

[[2]]
character(0)

[[3]]
character(0)

[[4]]
[1] "lattice"

[[5]]
character(0)
```

`type == "installed"` packages are already installed, so you don't need to deal with them.

**Comment by gaborcsardi** [comment]
Btw. you can also use the `binary` column, these are binary packages, so the dependencies can be ignored.
